name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
       # add start
      - name: Set lowercase repository name
        id: repo
        run: echo "REPO_LOWER=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        # add end
      - name: Build and push Docker image
        #uses: docker/build-push-action@v4
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}:latest
            ghcr.io/${{ env.REPO_LOWER }}:${{ github.sha }}
           
          #tags: |
            #ghcr.io/${{ github.repository_owner }}:latest
            #ghcr.io/${{ github.repository_owner }}:${{ github.sha }}
            # owner permet de recuperer le nom d'utilisateur
          #tags: |
            #ghcr.io/github.com/badraalou/my-kubernetes-ci-cd:latest
            #ghcr.io/github.com/badraalou/my-kubernetes-ci-cd:${{ github.sha }}
      - name: Update GitOps repository
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |
          # Configure git credential store
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
          
          # Remove any existing gitops directory
          rm -rf gitops
          
          # Clone repository using HTTPS URL without token
          # git clone https://github.com/rslim087a/grade-api-gitops.git gitops
          git clone https://github.com/BadraAlou/my-cicd-config.git gitops
          cd gitops
          
          if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i "s|image: ghcr.io/${{ env.REPO_LOWER }}:.*|image: ghcr.io/${{ env.REPO_LOWER }}:${{ github.sha }}|g" deployment.yaml
          else
            sed -i '' "s|image: ghcr.io/${{ env.REPO_LOWER }}:.*|image: ghcr.io/${{ env.REPO_LOWER }}:${{ github.sha }}|g" deployment.yaml
          fi
          
          # Commit changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          
          # Push
          #git push -f https://${GIT_TOKEN}@github.com/rslim087a/grade-api-gitops.git main
          git push -f https://${GIT_TOKEN}@github.com/${{ env.REPO_LOWER }}/my-cicd-config.git main
